PUT http://localhost:8080/events/2
content-type: application/json
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbnV4MTgyQGdtYWlsLmNvbSIsImV4cCI6MTcyODY3Nzg3MywidXNlcklkIjoxfQ.iGPajYgh9VXU7qTzlE7Qx3hp9cPjF008hKRUXAFy_-OfispRtvoRBiOK1qiFcXgAJacr0X6Lu0UyME7rrTrjRQ

{
  "id": 2,
  "name": "Test event updated",
  "description": "Test event updated",
  "location": "Test event location!",
  "dateTime": "2026-02-01T15:30:00.000Z",
  "user_id": 1
}