POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbnV4MTgyQGdtYWlsLmNvbSIsImV4cCI6MTcyODQwNzY5NiwidXNlcklkIjoxfQ.xUdkBoZM639ivp4JGUwi1shwqxY9M_N5FsVsW_jus84

{
  "name": "Test event two",
  "description": "A test event two",
  "location": "A test location",
  "dateTime": "2025-02-01T15:30:00.000Z",
  "user_id": 1
}
