PUT http://localhost:8080/events/2/unregister
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbWl2YWxsZUBnbWFpbC5jb20iLCJleHAiOjE3Mjg2ODg0MjIsInVzZXJJZCI6Mn0.tVokKfFSh4v6KAU_EM3hwYAFMbqiVK9losoxEvsqP-Fl-GNfiApO3FLN5CME7uiW7y_hB2YqJfRKnDY5QX6j-w