PUT http://localhost:8080/events/2/unregister
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbnV4MTgyQGdtYWlsLmNvbSIsImV4cCI6MTcyODk1MzA5NiwidXNlcklkIjoxfQ.j0AB3chK5qnyuJrCpyG3h2ScdjkzIA-R-lDGnd86enxoWrm_lRL90qscELoiDxk4KRpDFj7VB15UJbbOIY7JDw