PUT http://localhost:8080/events/4
content-type: application/json
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbWl2YWxsZUBnbWFpbC5jb20iLCJleHAiOjE3Mjk2MTkyOTcsInVzZXJJZCI6Mn0.vOo-awr34tmIyFp9IeS0icgUDZ6QS0Lha6USzNIzj8SOsVTdZ_xEnAUJuWCkaW4pS6ND-5WupqH8TFPelqzVEg

{
  "id": 4,
  "name": "Test event four updt",
  "description": "A test event four updt",
  "location": "A test location four updt",
  "dateTime": "2025-01-01T15:30:00Z",
  "user_id": 1
}