POST http://localhost:8080/events/1/register
authorization:  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbWl2YWxsZUBnbWFpbC5jb20iLCJleHAiOjE3Mjk2MjE3MzMsInVzZXJJZCI6Mn0.4YfrQDmnKnbdq8JsDaRtnCI4SEMoouwfi5O34PO8fX-nr-0urjTdHZ1Lal5dodH8UlMXcVwsgv-ai8bbNBM_0A