POST http://localhost:8080/events/2/register
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbWl2YWxsZUBnbWFpbC5jb20iLCJleHAiOjE3Mjg0NTkwMTIsInVzZXJJZCI6Mn0.RqFCRXHsXfuMmacSOibt3_-k2QDjwBXe5OSkCzDBW9DE32jhc3RWPNpwVhIFVO9SYDByodSjdG5N9MumDsHMyg