POST http://localhost:8080/events/2/register
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuZHJlZmVycmVpcmEuZGV2QGdtYWlsLmNvbSIsImV4cCI6MTcyODk1MTQ2OCwidXNlcklkIjowfQ.kZmvml4iEwAYiD_7YN9JPIs1U7gawWt2kZIfY3cJoploGNwJV0A00bxnFC66GqOCpMU5Gzlzi2k7LEl_e36y-w