GET http://localhost:8080/events/1/registrations
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbnV4MTgyQGdtYWlsLmNvbSIsImV4cCI6MTcyOTYyMTc4NywidXNlcklkIjoxfQ.TiC8vqN5lKMEpdEYF2SfeEJ_nVdF-a9CA-zMJtL1eMMWF3PVlX-74sTMjQDCxaIN8Ce1VDV1xJbTGOO0EiUWaQ