GET http://localhost:8080/events/2/registrations
authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbnV4MTgyQGdtYWlsLmNvbSIsImV4cCI6MTcyODk1MjIzMSwidXNlcklkIjoxfQ.urm6m-9DR2QROsi2S-q22B9YYQieMOG-bf3fqZRLbVfQoSlEEuWMKi-iEIRarhn0838xxrPTC5Qz2i0HoPw6tA