POST http://localhost:8080/login
content-type: application/json

{
"email": "adnux182@gmail.com",
"password": "123"
}

# "email": "adnux182@gmail.com",
# "password": "123"

# "email": "andreferreira.dev@gmail.com",
# "password": "456"