// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64
	Name        string
	Description string
	Location    string
	Datetime    time.Time
	UserID      int64
}

type Registration struct {
	ID      int64
	EventID int64
	UserID  int64
	Active  bool
}

type User struct {
	ID        int64
	Email     string
	Password  string
	FirstName sql.NullString
	LastName  sql.NullString
}
